### ISSUE TITLE
Payload created but unable to encrypt

### ISSUE THREAD

**Issue by buggii** [GaryOderNichts/alarmo#2]
Compiling using pycryptodome i receive this error:

....
stm32h7xx_hal.c
startup_stm32h730xx.s
linking ... usb_payload.elf
creating ... usb_payload.bin
encrypting ... a.bin
Traceback (most recent call last):
  File "/home/test/alarmo/usb_payload/ciphtool.py", line 10, in <module>
    RSA_MOD = int.from_bytes([
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
make[1]: *** [/home/test/alarmo/usb_payload/Makefile:173: /home/test/alarmo/usb_payload/a.bin] Error 1
make: *** [Makefile:153: build] Error 2

Key added as the following example (not real key):
AES_KEY = b'0102003040506070809010111213141516'
tested also as (withs ame result):
AES_KEY = b'\x01\x02\x00\x30\x40\x50\x60\x70\x80\x90\x10\x11\x12\x13\x14\x15\x16'

Tested adding "big" as data type but i receive an RSA error. Which crypto libs should I use ?

**Comment by GaryOderNichts** [comment]
The issue isn't from the crypto module you're using, but from the built-in python types. You need to use at least python version 3.11.

The key and IV should be used in the `AES_KEY = b'\x01\x02\x00\x30\x40\x50\x60\x70\x80\x90\x10\x11\x12\x13\x14\x15\x16'` format. Also make sure to not add the zero counter at the end of the IV.

**Comment by GaryOderNichts** [comment]
I've updated the tool and tested it successfully on python version 3.8.20.

**Comment by buggii** [comment]
Great ! It works now ! 

I had to remove that line otherwise it won't compile:

		-Wl,--no-warn-rwx-segments


What tool should I use to convert images to the correct format? I tested some without success (garbage on screen).

**Comment by GaryOderNichts** [comment]
You can do something like this to create an include file with the image data.
```py
from PIL import Image
import sys

image = Image.open(sys.argv[1])

width, height = image.size

rgb_img = image.convert('RGB')

count = 0

print('static uint8_t image_data[] = {')

for x in range(width):
    for y in range(height):
        pixel = rgb_img.getpixel((x, y))
        r, g, b = pixel
        print(f"0x{b:02x}, 0x{g:02x}, 0x{r:02x}, ", end='')

        count += 1

    if (count % 16) == 0:
        print()

print('};')
```

**Comment by buggii** [comment]
Good ! Thank you !
Now the image is displayed but it is "mirrored" horizontally like this: https://www.fixmyambulance.com/v/vspfiles/photos/4%20Mirror%20Image%20ECNALUBMA-2T.gif

If i mirror the image before the script convertion the result is a garbled image.

Can you help me updating the above script ?

Solved: need to rotate and flip the image.

**Comment by GaryOderNichts** [comment]
You can also iterate over the x axis in reversed order:
```
for x in reversed(range(width)):
```
